### ISSUE TITLE
Doesn't compile on windows

### ISSUE THREAD

**Issue by ahmetb** [Bitbored/go-ansicon#1]
I get compilation error:

```
$ GOOS=windows go build
# github.com/bitbored/go-ansicon/windows/display
windows/display/display.go:55: invalid operation: charInfo.Char[1] (type interface {} does not support indexing)
```

**Comment by seppestas** [comment]
Ow, this is definitely a mistake. I probably forgot to stage this file when changing the way charInfo is represented. To bad the working code is probably lost in a destroyed VM.

I will try to fix this as soon as I get a Windows VM working on my new laptop :)

**Comment by klauspost** [comment]
Any outlook on a fix for this? The package seems kind of useless without Windows support.

I changed the problematic line to 

``` Go
charInfo.Char = ' '
```

But I have no idea if it is correct.

**Comment by ahmetb** [comment]
In the meanwhile we released https://github.com/Azure/go-ansiterm which is used in Docker client for Windows today. You might want to check that out.  

—Alp
http://alp.im

**Comment by seppestas** [comment]
Yeah, this project is pretty useless at the moment, sorry for that.

I started fixing this issue, and decided that the way I handle unions in Go is not the proper way to do it, which meant a pretty big rewrite of some code. I mostly finished this, but for some reason I did not commit anything yet.

The biggest problem is that I don't use this project myself anymore, making it pretty hard for this project to survive. Also, I don't use my Windows VM anymore, and out of sight is out of mind...
I will try to push my changes to this repo this evening, but it might be better to check out go-ansiterm instead of using this library.

Even though I have yet to test it myself, it looks pretty promising. Judging from the code they seem to have implemented some sort of keyboard code conversion as well, which is something this library does not do (meaning: you can't send keyboard interrupts to remote servers when e.g using my ssh client on Windows). Maybe I can merge some code of my project into go-ansiterm...

**Comment by seppestas** [comment]
@klauspost could you check if it works now? Apparently I already fixed this a long time ago, but I did not push it to github :flushed:

**Comment by klauspost** [comment]
Very cool! It compiles now, but I cannot test it until tomorrow. I will report back, so you can hopefully close this!

**Comment by seppestas** [comment]
KK. It might be best to check out go-ansiterm though. It seems like that project is more alive than this project, and I haven't even fully completed this project yet. I will see if it has the same functionality, and if it does I'm planning to put a link to that project in this project's readme.

I'm not really planning to actively maintain this project anymore...

**Comment by klauspost** [comment]
Yes, it compiles, and appears to work fine.

Thanks a bunch!
